version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 1202212022AaAa
      PGDATA : /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data:Z